### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by tantalor** [chaowentan/Purify#6]
I tried the first blog post I had open, http://www.greeblemonkey.com/2013/01/the-instagram-conundrum.html and got this error.

```
Error in event handler for 'undefined': Cannot read property 'document' of undefined TypeError: Cannot read property 'document' of undefined
    at ArticleView._createAndAppendFrame (chrome-extension://kjiappjpfpaekdfeioanaphpihpojemc/js/ArticleView.js:69:30)
    at new window.ArticleView (chrome-extension://kjiappjpfpaekdfeioanaphpihpojemc/js/ArticleView.js:21:29)
    at chrome-extension://kjiappjpfpaekdfeioanaphpihpojemc/js/content_script.js:9:11
    at chrome.Event.dispatchToListener (event_bindings:387:21)
    at chrome.Event.dispatch_ (event_bindings:373:27)
    at chrome.Event.dispatch (event_bindings:393:17)
    at miscellaneous_bindings:165:35
    at chrome.Event.dispatchToListener (event_bindings:387:21)
    at chrome.Event.dispatch_ (event_bindings:373:27)
    at chrome.Event.dispatch (event_bindings:393:17) 
```

**Comment by chaowentan** [comment]
Thanks for reporting this issue!  It turned out this run time error only shows up in the stable release, but not in the dev release (which was the only installation that I had.) I also found a parsing error caused by the unusual html structure in that website. Both of these errors are fixed and should be pushed to the web store soon.
